// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjjKj23MqsBoyfDF8EvZLNYHIVA95B-yw',
    appId: '1:749268540112:web:9fc7b20597ccb1b3c75cd5',
    messagingSenderId: '749268540112',
    projectId: 'chatapp-f5c8c',
    authDomain: 'chatapp-f5c8c.firebaseapp.com',
    storageBucket: 'chatapp-f5c8c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALMshLhDFuS6hBI3pisySoerTND_05Ppk',
    appId: '1:749268540112:android:8198614f6e2f876dc75cd5',
    messagingSenderId: '749268540112',
    projectId: 'chatapp-f5c8c',
    storageBucket: 'chatapp-f5c8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqSuYyu6FdJ0ChTYMkLDa089dGElXCjko',
    appId: '1:749268540112:ios:3de8231cdc5fbb2fc75cd5',
    messagingSenderId: '749268540112',
    projectId: 'chatapp-f5c8c',
    storageBucket: 'chatapp-f5c8c.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqSuYyu6FdJ0ChTYMkLDa089dGElXCjko',
    appId: '1:749268540112:ios:3de8231cdc5fbb2fc75cd5',
    messagingSenderId: '749268540112',
    projectId: 'chatapp-f5c8c',
    storageBucket: 'chatapp-f5c8c.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjjKj23MqsBoyfDF8EvZLNYHIVA95B-yw',
    appId: '1:749268540112:web:ffa466d8740f77cac75cd5',
    messagingSenderId: '749268540112',
    projectId: 'chatapp-f5c8c',
    authDomain: 'chatapp-f5c8c.firebaseapp.com',
    storageBucket: 'chatapp-f5c8c.appspot.com',
  );
}
